Add NUnit GHA test reporter
This reports the unit tests in a format GHA can display in the PR

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -32,4 +32,12 @@ jobs:
         run: dotnet build src/solid.sln --no-restore
 
       - name: Run NUnit Tests
-        run: dotnet test output/net461/*Tests.dll  --filter "TestCategory != SkipOnCI" --no-build -- NUnit.TestOutputXml=TestResults
+        run: dotnet test output/net461/*Tests.dll  --filter "TestCategory != SkipOnCI" --no-build -- NUnit.TestOutputXml=TestResults.xml
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: NUnit Tests
+          path: TestResults.xml
+          reporter: java-junit 
